run:
  timeout: 30s

linters-settings:
  errcheck:
    check-blank: true
  gocognit:
    min-complexity: 10
  gofumpt:
    lang-version: "1.17"
  gosimple:
    go: "1.17"
    checks: [ "all" ]
  govet:
    check-shadowing: true
  lll:
    line-length: 120
    tab-width: 1
  misspell:
    locale: US
  staticcheck:
    go: "1.17"
    checks: [ "all" ]
  whitespace:
    multi-if: true
    multi-func: true


linters:
  fast: false
  disable-all: true
  enable:
    - errcheck
    - gocognit
    #    - gofumpt # conflict with gci
    - gosimple
    - govet
    - lll
    - misspell
    - staticcheck
    - whitespace
    - bidichk
    - cyclop
    - dogsled
    - dupl
    - errorlint
    - exhaustive
    - funlen
    - gci
    - goheader
    #    - goimports
    - golint
    - gomnd
    - gomoddirectives
    - gomodguard
    - gosec
    - depguard
    - ifshort
    - importas
    - ireturn
    - makezero
    - maligned
    - nakedret
    - nestif
    - nilnil
    - nlreturn
    - nolintlint
    - prealloc
    - promlinter
    - predeclared
    - rowserrcheck
    - revive
    - staticcheck
    - stylecheck
    - tagliatelle
    - thelper
    - tenv
    - unparam
    - unused
    - varnamelen
    - wrapcheck
