name: CI

on:
  push:
    branches:
      - main

jobs:
  lint:
    name: Run linter
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Run build
        run: docker-compose build dev app

      - name: Run lint
        run: docker-compose run --rm dev pre-commit run -a

      - name: Run tests
        run: docker-compose run --rm dev go test ./app/...
